farma_inventory:
    resource: "@FarmaInventoryBundle/Controller/"
    type:     annotation
    prefix:   /api

farma_app:
    resource: "@FarmaAppBundle/Controller/"
    type:     annotation
    prefix:   /

farma_user:
    resource: "@FarmaUserBundle/Controller/"
    type:     annotation
    prefix:   /api

farma_base:
    resource: "@FarmaBaseBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
