security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        farma_firewall:
            pattern: ^/
            anonymous: true
            form_login:
                provider: in_memory
                login_path: _base_login
                check_path: _base_security_check
                #success_handler: user.listener.login
                use_referer: true
            logout:
                path: _base_logout
                target: base_homepage

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }