security:
    encoders:
        Farma\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SALES:       [ROLE_USER]
        ROLE_INVENTORY:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_SALES, ROLE_INVENTORY]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        farma_provider:
            entity:
                class: FarmaUserBundle:User
                property: email

    firewalls:
        farma_firewall:
            pattern: ^/
            anonymous: true
            form_login:
                provider: farma_provider
                login_path: _base_login
                check_path: _base_security_check
                success_handler: base.listener.login
                use_referer: true
            logout:
                path: _base_logout
                target: base_homepage

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app, roles: ROLE_USER }