security:
    encoders:
        Farma\BaseBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        farma_provider:
            entity:
                class: FarmaBaseBundle:User
                property: username

    firewalls:
        farma_firewall:
            pattern: ^/
            anonymous: true
            form_login:
                provider: farma_provider
                login_path: _base_login
                check_path: _base_security_check
                success_handler: base.listener.login
                use_referer: true
            logout:
                path: _base_logout
                target: base_homepage

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }